name: smart_doc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  uuid: ^4.0.0
  cupertino_icons: ^1.0.6
  google_mlkit_text_recognition: ^0.11.0
  image_picker: ^1.1.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  camera: ^0.10.5
  image: ^4.1.7
  image_cropper: ^7.0.3
  google_mlkit_document_scanner: ^0.4.0
  pdf: ^3.10.8
  firebase_storage: ^11.7.0
  path_provider: ^2.0.11
  shared_preferences: ^2.2.3
  provider: ^6.1.5+1
  file_picker: ^8.0.0+1
  permission_handler: ^11.0.1
  supabase_flutter: ^2.5.4
  url_launcher: ^6.1.11
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.2
  firebase_messaging: ^14.9.4
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/loader.json

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
